services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mot de passe root pour MySQL
    volumes:
      - C:\Users\pc\mysql_data:/var/lib/mysql    # Persistance des données
    ports:
      - "3306:3306"                     # Expose le port MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db                       # Lie phpMyAdmin au service MySQL
      PMA_PORT: 3306                     # Port de MySQL
    ports:
      - "8080:80"                        # Expose phpMyAdmin sur le port 8080
    depends_on:
      - db                               # Dépend du service MySQL

volumes:
  mysql_data:
